### PR TITLE
add a file

### PR DESCRIPTION
**Pull request by howard50b**

### CODE REVIEW

**Comment by sahuguet** [comment]
Fix your code and enter a valid JSON, please.

**Comment by ghost** [comment]
In future assignments you will lose points for submitting obviously incorrect code.

**Comment by howard50b** [comment]
Got it! Sorry about that. I was just trying to see what would happen if the file wasn't in a json format. I've committed a new file with the correct format. Won't happen again.

**Comment by ghost** [comment]
Sure no problem!

**Pull request closed without merging**
